### ISSUE TITLE
Create contribution guidelines in Readme 

### ISSUE THREAD

**Issue by sahilverma0696** [sahilverma0696/promt.live-interviews#10]
This segment is needed to be created for,
1. folks contributing directly from github
2. interviewees coming from sessions.

Standard changes 
Fork, pull, commit, make pull request 
But, with these one needs to make changes in the readme accordingly.

 important link which tells the idea of readme :
 https://github.com/sahilverma0696/promt.live-interviews/issues/2#issuecomment-1407599212

**Comment by the-amazing-atharva** [comment]
Hi!

Like to add a general contributing section in README right?
I would like to work on this issue

**Comment by sahilverma0696** [comment]
Cool,
Just make sure the details are provided in very layman's terms. As a lot of contributors can be beginners.
Thanks

**Comment by the-amazing-atharva** [comment]
Thoughts??

Also should I add a specific guide for code contributions?

![image](https://user-images.githubusercontent.com/121221252/215476393-8b9b1448-d4ce-43e4-9f0b-10453392c88e.png)

**Comment by the-amazing-atharva** [comment]
![image](https://user-images.githubusercontent.com/121221252/215481057-705537a5-dcaa-4fd0-88e9-e8462ad6094a.png)

**Comment by sahilverma0696** [comment]
Perfect 
generate the pr

**Comment by sahilverma0696** [comment]
Kudos
