### ISSUE TITLE
[OTHER] Broken Link in README

### ISSUE THREAD

**Issue by Rishav1707** [sahilverma0696/promt.live-interviews#3]
![broken](https://user-images.githubusercontent.com/97666287/215283799-ed76382c-06f3-49cc-9c26-2f031a892179.png)

**Comment by sahilverma0696** [comment]
Hey thank you for marking this issue.
Please let me know if you wish to take on the same, 
Also there is https://github.com/sahilverma0696/promt.live-interviews/issues/2
if you would like to take as this becomes the part of the same

**Comment by Rishav1707** [comment]
What do you want in the `README`?

**Comment by sahilverma0696** [comment]
Well basic idea is to give reference to the channel,

Iteration 1:
And with each code pushed after the session, the readme is required to be updated with 
1. The question ( which might or might not be present on leetcode and other platform, majorly 2/3 questions will be )
2. The link to the code which was solved in the session ( which is uploaded to this repository e.g., https://github.com/sahilverma0696/promt.live-interviews/blob/main/DSA%20sessions/24Jan/question1.py )
3. Study reference to the question, this is an external link, which can be a link to understand the question or the topic, which can be a leetcode post, or a whitepaper or even some other video as reference )


This is the core idea, as the readme will be working as an index to all the code.

Iteration 2:
Beautify the readme 

Iteration 3:
Copy this core to the upcoming website and then similarly this information will be present here as well as on the website.

NOTE:  This repo(or a repo ) will be kept active even after the website, reason being, 
1. the interviewees do post out the right solution, after the LIVE session.
2. Its important to teach people about contribution and building this, so this will be developed as a community and not just by a single team.


This is what I currently have in my mind.
Cheers!!

**Comment by sahilverma0696** [comment]
Gracias 🙏
